print("Hi my name is RudeAI")
print("I'd like to ask you a few questions")
ID = input("What is your name?")
print("Wow" , ID, "... You must have such...interesting...parents")
num1 = int (input("How old are you?"))
print("Dang..." , num1, "is old... have you started thinking about what your tombstone will say yet?")
act = input("What do you like to do for fun")
print("Wow, I used to" , act, "but then I turned 5 and decided I was too old for that")
mus = input("What kind of music do you like?")
print("I was under the impression that" , mus, "was for little girls, but I guess thats alright")
sib = int (input("How many siblings do you have?"))
print("Well I sure hope that your" , sib, "siblings aren't as lame as you.")
job = input("What do you want to be when you grow up?")
print("It would probably be smart to not even try to be a" , job, "and shoot for something more realistic like a hot dog vendor")
print("So," , ID, "I have learned that you are" , num1, "years old, like to" , act, ", enjoy listening to" , mus, ", and have" , sib, "siblings. Good luck becoming a" , job, "and have a nice day.")
