print("                     xxxxxxxxxx")
print("                    x          x")
print("                   x   o    o   x")
print("                   x            x")
print("                   x      L     x")                  
print("                   x            x")
print("                   x   \_____/  x")
print("                    x          x")
print("                     xxxxxxxxxx")
print("                          x")
print("           #--------------x-------------#")
print("                          x")
print("                          x")
print("                          x")
print("                          x")
print("                          x")
print("                          x")
print("                          x")
print("                          /\ ")
print("                         /  \ ")
print("                        /    \ ")
print("                       /      \ ")
print("                      /        \ ")
print("                     /          \ ") 
